---
- name: Setup server
  hosts: webservers
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Ensure docker is installed
      apt:
        name: docker.io
        state: present

    - name: Ensure docker service is running and enabled
      service:
        name: docker
        state: started
        enabled: yes
